### PR TITLE
Add betydb_query code to UI

### PR DESCRIPTION
**Pull request by kimberlyh66**
This addresses #29.

`betydb_query` code is displayed for selected experiment and trait.

Changes have been made to the cache-refresh.R script, so it will have to be rerun.

### CODE REVIEW

**Comment by kimberlyh66** [comment]
Do you mean the value of `limit` is always `none`? Do you think we should remove this parameter?

**Comment by dlebauer** [comment]
Sorry I mean the value of trait is always `''` when I was clicking around

**Comment by kimberlyh66** [comment]
Did you rerun the cache-refresh.R script - I made some changes to it again that affects what is displayed in `trait=`  part of query

**Comment by dlebauer** [comment]
I did rerun but maybe it didn't replace the file. I'll check again

________________________________

**Comment by kimberlyh66** [comment]
Changes have been made to add a downloads tab to the UI.

**Pull request merged**
