### PR TITLE
Add variable and method tables containing BETYdb links

### PR DESCRIPTION
**Pull request by kimberlyh66**
This addresses issue #37.

Tables have been added below the trait plot containing variable and method information. Clickable links to BETYdb records are included in tables.

### CODE REVIEW

**Comment by dlebauer** [comment]
I see a methods table but not a variables table; perhaps this is due to the error

image


Also, is it possible to make the method or variable name as a hyperlink rather than providing the link as a separate column? And add the description as a separate column?

**Comment by kimberlyh66** [comment]
@dlebauer I have hyperlinked the variable / method names and added the descriptions as a separate column. 

I made a minor edit to the cache.refresh script to change how the updated cache data is being saved. I think the error that you are having with the variables table is a result of using an old version of the cached data. I think rerunning the cache.refresh script should solve the problem.

**Comment by dlebauer** [comment]
@kimberlyh66 
- if I try and run the cache-refresh.R when the cache.RData exists, I immediately get the message:
>  "Completed cache refresh properly."
- if I delete cache.RData and run the script I get the message:
> Completed cache refresh properly.
Warning message:
In file.rename(cache_path_temp, cache_path) :
  cannot rename file './cache/cache.RData.tmp' to './cache/cache.RData', reason 'No such file or directory'

Do you know what I am doing wrong, or what do you do to refresh the cache?

**Comment by dlebauer** [comment]
my previous comment was resolved - I forgot to run the final sync command `docker-compose run --rm bety sync`

**Comment by dlebauer** [comment]
Looks good - added a few tweaks to remove the title of the tables, styling could be improved in the future, but the required information is present in the appropriate place, and the links are great!

image

**Pull request merged**
